# Generated by Django 5.2.4 on 2025-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='always_active',
            field=models.BooleanField(default=False),
        ),
    ]
