# Generated by Django 5.2.4 on 2025-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_always_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='stock_symbol',
            field=models.CharField(choices=[('AAPL', 'Apple Inc.'), ('TSLA', 'Tesla Inc.'), ('GOOGL', 'Alphabet Inc.'), ('MSFT', 'Microsoft Corp'), ('AMZN', 'Amazon.com Inc.'), ('META', 'Meta Platforms Inc.'), ('NVDA', 'NVIDIA Corporation'), ('INTC', 'Intel Corporation'), ('NFLX', 'Netflix Inc.'), ('BABA', 'Alibaba Group')], default='AAPL', max_length=10),
        ),
    ]
