# Generated by Django 5.2.4 on 2025-08-04 20:51

import alerts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='stock_symbol',
            field=models.CharField(max_length=10, validators=[alerts.validators.validate_stock_symbol]),
        ),
    ]
