# Generated by Django 5.2.4 on 2025-08-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_alert_stock_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='always_active',
        ),
    ]
