# Generated by Django 5.2.4 on 2025-08-07 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_remove_alert_always_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
